export const DATA = [
  {
      "PortfolioCompany": null,
      "Fund": "IGF Mgmt Ltd",
      "FundType": "Mgmt",
      "MailingID": 30116,
      "MailingDate": "2025-07-09T00:00:00",
      "Subject": "SC India GF Management I Ltd Cash Call Due 8/30/25",
      "EventDate": "30 Aug, 2025",
      "MailingType": "CCall",
      "MailingTypeName": "Cash Call",
      "MySequoiaHTML": "SC India GF Management I Ltd is issuing a call for capital. The funds are due on August 30, 2025. See below for a breakdown of your contribution due.",
      "SectionName": "Recent Activity",
      "SortOrder": 9999,
      "DateLastViewed": null,
      "CountActionRequired": null,
      "MailingRecipientNotificationID": null
  },
  {
    "PortfolioCompany": null,
    "Fund": "IGF Mgmt Ltd",
    "FundType": "Mgmt",
    "MailingID": 30116,
    "MailingDate": "2025-07-09T00:00:00",
    "Subject": "SC India GF Management I Ltd Cash Call Due 8/30/25",
    "EventDate": "30 Aug, 2025",
    "MailingType": "CCall",
    "MailingTypeName": "Cash Call",
    "MySequoiaHTML": "SC India GF Management I Ltd is issuing a call for capital. The funds are due on August 30, 2025. See below for a breakdown of your contribution due.",
    "SectionName": "Recent Activity",
    "SortOrder": 9999,
    "DateLastViewed": null,
    "CountActionRequired": null,
    "MailingRecipientNotificationID": null
},
{
  "PortfolioCompany": null,
  "Fund": "IGF Mgmt Ltd",
  "FundType": "Mgmt",
  "MailingID": 30116,
  "MailingDate": "2025-07-09T00:00:00",
  "Subject": "SC India GF Management I Ltd Cash Call Due 8/30/25",
  "EventDate": "30 Aug, 2025",
  "MailingType": "CCall",
  "MailingTypeName": "Cash Call",
  "MySequoiaHTML": "SC India GF Management I Ltd is issuing a call for capital. The funds are due on August 30, 2025. See below for a breakdown of your contribution due.",
  "SectionName": "Recent Activity",
  "SortOrder": 9999,
  "DateLastViewed": null,
  "CountActionRequired": null,
  "MailingRecipientNotificationID": null
},
{
  "PortfolioCompany": null,
  "Fund": "IGF Mgmt Ltd",
  "FundType": "Mgmt",
  "MailingID": 30116,
  "MailingDate": "2025-07-09T00:00:00",
  "Subject": "SC India GF Management I Ltd Cash Call Due 8/30/25",
  "EventDate": "30 Aug, 2025",
  "MailingType": "CCall",
  "MailingTypeName": "Cash Call",
  "MySequoiaHTML": "SC India GF Management I Ltd is issuing a call for capital. The funds are due on August 30, 2025. See below for a breakdown of your contribution due.",
  "SectionName": "Recent Activity",
  "SortOrder": 9999,
  "DateLastViewed": null,
  "CountActionRequired": null,
  "MailingRecipientNotificationID": null
},
{
  "PortfolioCompany": null,
  "Fund": "IGF Mgmt Ltd",
  "FundType": "Mgmt",
  "MailingID": 30116,
  "MailingDate": "2025-07-09T00:00:00",
  "Subject": "SC India GF Management I Ltd Cash Call Due 8/30/25",
  "EventDate": "30 Aug, 2025",
  "MailingType": "CCall",
  "MailingTypeName": "Cash Call",
  "MySequoiaHTML": "SC India GF Management I Ltd is issuing a call for capital. The funds are due on August 30, 2025. See below for a breakdown of your contribution due.",
  "SectionName": "Recent Activity",
  "SortOrder": 9999,
  "DateLastViewed": null,
  "CountActionRequired": null,
  "MailingRecipientNotificationID": null
},
]